# Generated by Django 3.0.8 on 2020-10-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=50)),
                ('aadhar', models.CharField(max_length=50)),
                ('voter_id', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('inputCity', models.CharField(max_length=50)),
                ('inputZip', models.CharField(max_length=50)),
                ('id_proof', models.CharField(max_length=50)),
            ],
        ),
    ]
