# Generated by Django 3.0.8 on 2020-11-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='aadhar',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='id_proof',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='inputCity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='inputZip',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='voter_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
